### ISSUE TITLE
Let there be LICENSE 

### ISSUE THREAD

**Issue by suvojit-0x55aa** [shin-migami/CurveSim#12]

**Comment by Lyxnx** [comment]
I'll take this. What license would be most suitable?

**Comment by suvojit-0x55aa** [comment]
MIT I guess

**Comment by Lyxnx** [comment]
Created PR, although it looks like someone got there before me

**Comment by suvojit-0x55aa** [comment]
Thanks for your contribution anyways can't merge this because someone
already made a PR. Keep contributing :)
