### ISSUE TITLE
Add Return const reference from functions

### ISSUE THREAD

**Issue by suvojit-0x55aa** [shin-migami/CurveSim#3]

**Comment by prashant2018** [comment]
HI, could you elaborate the issue please

**Comment by suvojit-0x55aa** [comment]
@prashant2018 Currently fer objects are passed to the function as refernces. Example -
![PAssed by Reference](https://cloud.githubusercontent.com/assets/10397574/19020947/c0b297ba-88d3-11e6-81db-61f89f4f5393.png)

I think it would be better if we pass them as const refernce for those object that doesn't get modified by the function
![after](https://cloud.githubusercontent.com/assets/10397574/19020953/e653b53a-88d3-11e6-9d1d-8bbd42792c6a.png)

It would give an immediate understanding what objects the function is changing.

**Comment by yunchih** [comment]
Hi, is someone working on this?
If not, I think I can try working on this.

**Comment by suvojit-0x55aa** [comment]
@yunchih Please go ahead. That would be very kind of you
