### ISSUE TITLE
Add name of contributors

### ISSUE THREAD

**Issue by suvojit-0x55aa** [shin-migami/CurveSim#7]

**Comment by sourabhtk37** [comment]
OK,on it.Assign it to me.

Do you want to add the list of contributors as a section in Readme.md or a seperate file?

**Comment by suvojit-0x55aa** [comment]
@sourabhtk37 Please go ahead
You cand add it in the README itself

**Comment by suvojit-0x55aa** [comment]
If possible with their avatars

**Comment by sourabhtk37** [comment]
Done.
